example: # Name of bouncy ball
  projectile:
    # See Types (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
    item: SNOWBALL

    # Initial velocity of the snowball when thrown
    launch-velocity: 1.5

    # At what speed the snowball will disintegrate (velocity > threshold)
    threshold: 0.25

    # Velocity damped when it hits a service (velocity *= damping)
    damping: 0.75

    # Snowball will return into your inventory if it hits you.
    returns: true

    # Snowball will be removed once you launch it from your inventory
    removes: true

    # Snowball will drop as an item when it stops bouncing.
    drops: true

    # Blocks the projectile can bounce on. Set to blocks: [] if you want it to bounce on everything!
    blocks:
      - GRASS_BLOCK
      - SNOW_BLOCK
      - DIRT

  particle:
    # See types (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html)
    type: SNOW_SHOVEL

    # How many particles spawn at the projectile Location
    amount: 1
fireball:
  projectile:
    item: FIRE_CHARGE
    launch-velocity: 1.0
    threshold: 0.5
    damping: 0.5
    returns: false
    drops: false
    removes: false
    blocks: []
  particle:
    type: FLAME
    amount: 1
slime_ball:
  projectile:
    item: SLIME_BALL
    launch-velocity: 1.2
    threshold: 0.3
    damping: 0.6
    returns: false
    removes: true
    drops: false
    blocks: []
  particle:
    type: SLIME
    amount: 1